'use strict';
(() => {
const canvas=document.getElementById('sea'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),TAU=Math.PI*2,W=1440,H=900,CX=W/2,CY=H/2;
let scale=1,ox=0,oy=0,state='menu',easy=false,muted=false,audio,master,last=0,clock=0,acc=0;
let player,enemies=[],shots=[],hostile=[],drops=[],particles=[],rings=[],wave=0,waveTime=0,spawnTimer=0,score=0,kills=0,beacon=100,shake=0,notice=0,boss=null,bossStarted=false,choices=[],runTime=0,best=0;
const keys=new Set(),mouse={x:CX,y:CY,down:false};
const stars=Array.from({length:120},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.4+.3,p:Math.random()*TAU}));
try{best=Number(localStorage.getItem('lastlight-best'))||0;}catch{}
$('best').textContent=`FIVE TIDES. ONE LEVIATHAN. ONE DAWN.    /    BEST ${best.toLocaleString()}`;
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;scale=Math.min(innerWidth/W,innerHeight/H);ox=(innerWidth-W*scale)/2;oy=(innerHeight-H*scale)/2;ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function sound(freq=300,dur=.1,type='sine',gain=.06,slide=.5){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*slide),audio.currentTime+dur);g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(master);o.start();o.stop(audio.currentTime+dur);}
function initAudio(){try{if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.7;master.connect(audio.destination);}audio.resume();}catch{}}
let noteTimer=0,noteIndex=0;
function music(dt){if(!audio||muted)return;noteTimer-=dt;if(noteTimer<=0){noteTimer=.48;const notes=[110,164.81,220,261.63,146.83,220,293.66,220];sound(notes[noteIndex++%8],.9,'sine',.018,1);if(noteIndex%4===0)sound(55,.4,'triangle',.035,.75);}}
const rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function text(s,x,y,size=15,color='#bdd1d0',align='left'){ctx.fillStyle=color;ctx.font=`${size}px Segoe UI, Arial`;ctx.textAlign=align;ctx.fillText(s,x,y);}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,Math.max(0,r),0,TAU);ctx.fill();}
function burst(x,y,color,n=14,power=120){for(let i=0;i<n;i++){const a=rnd(0,TAU),v=rnd(20,power);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:rnd(.25,.8),max:.8,r:rnd(1.5,4),color});}}
function ring(x,y,color,max=160){rings.push({x,y,r:8,max,life:.5,color});}
function toast(s){$('toast').textContent=s;notice=4;}
function hide(){for(const id of ['menu','pause','choice','ending'])$(id).classList.add('hidden');}
function begin(){initAudio();hide();state='playing';player={x:CX,y:CY+135,hp:easy?130:100,max:easy?130:100,speed:245,damage:19,rate:.25,fire:0,dash:0,dashTime:0,dx:0,dy:-1,inv:1,pulse:0,pulseMax:8,multi:1,pierce:0,magnet:115,regen:0};enemies=[];shots=[];hostile=[];drops=[];particles=[];rings=[];wave=0;score=0;kills=0;beacon=100;runTime=0;boss=null;bossStarted=false;nextWave();}
const names=['THE FIRST RIPPLE','TEETH IN THE CURRENT','THE WRECKING CHOIR','A SEA OF EMBERS','THE DEEP OPENS'];
function nextWave(){wave++;waveTime=0;spawnTimer=1.5;state='playing';hide();toast(`TIDE ${wave} / 5  ·  ${names[wave-1]}`);sound(440,.7,'sine',.08,1.5);}
const upgrades=[
{name:'Hot brass',desc:'+35% weapon damage. Every round makes a stronger argument.',apply:()=>player.damage*=1.35},
{name:'Clockwork feed',desc:'Fire 22% faster. The mechanism sings through the spray.',apply:()=>player.rate*=.78},
{name:'Forked lightning',desc:'Add another projectile to each volley, up to five.',valid:()=>player.multi<5,apply:()=>player.multi++},
{name:'Ironclad',desc:'+35 maximum hull and fully repair your ship.',apply:()=>{player.max+=35;player.hp=player.max;}},
{name:'Storm engine',desc:'+20% movement speed. Dash cooldown falls by 20%.',apply:()=>{player.speed*=1.2;player.dashMod=(player.dashMod||1)*.8;}},
{name:'Deep resonance',desc:'Shockwave recharges 25% faster and its damage increases.',apply:()=>{player.pulseMax*=.75;player.pulseDamage=(player.pulseDamage||50)+30;}},
{name:'Salvage heart',desc:'Double collection reach. Slowly regenerate hull at sea.',valid:()=>!player.regen,apply:()=>{player.magnet*=2;player.regen=1.2;}},
{name:'Ghost rounds',desc:'Rounds pierce one additional target. +15% damage.',apply:()=>{player.pierce++;player.damage*=1.15;}}
];
function dock(){state='upgrade';hostile=[];shots=[];for(const d of drops){score+=20;beacon=Math.min(100,beacon+2);}drops=[];player.hp=Math.min(player.max,player.hp+35);beacon=Math.min(100,beacon+25);choices=upgrades.filter(u=>!u.valid||u.valid()).sort(()=>Math.random()-.5).slice(0,3);$('dockLabel').textContent=`TIDE ${wave} SURVIVED · ${score.toLocaleString()} POINTS`;$('cards').replaceChildren();choices.forEach((u,i)=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<div class="num">0${i+1} / SALVAGED TECHNOLOGY</div><strong>${u.name}</strong><span>${u.desc}</span>`;b.onclick=()=>choose(i);$('cards').append(b);});$('choice').classList.remove('hidden');sound(330,.5,'triangle',.07,2);}
function choose(i){if(state!=='upgrade'||!choices[i])return;choices[i].apply();nextWave();}
function finish(win,reason=''){state=win?'won':'lost';hide();score+=win?Math.round(2000+player.hp*10+beacon*10):0;best=Math.max(best,score);try{localStorage.setItem('lastlight-best',String(best));}catch{}$('endBadge').textContent=win?'DAWN FOUND YOU':'THE LIGHT WILL BE REMEMBERED';$('endTitle').textContent=win?'And then, the sea turned gold.':'One more light in the deep.';$('endText').textContent=win?'The Leviathan sinks. Beyond the thinning fog, other lanterns answer yours. You were never the last. You were simply the first to hold on.':reason+' The keeper leaves a fresh lantern on the dock. There is always another voyage.';$('endStats').textContent=`${score.toLocaleString()} points · ${kills} creatures defeated · ${Math.floor(runTime/60)}m ${Math.floor(runTime%60)}s at sea · Best ${best.toLocaleString()}`;$('ending').classList.remove('hidden');sound(win?523:180,1.5,'sine',.12,win?1.5:.3);}
function spawn(type){let a=rnd(0,TAU),x=CX+Math.cos(a)*820,y=CY+Math.sin(a)*550;const spec={drifter:[28,48,15,'#d28975'],hunter:[23,105,12,'#efb578'],spitter:[48,38,19,'#ba94d0'],brute:[125,30,28,'#dc6d68']}[type];enemies.push({x:clamp(x,20,W-20),y:clamp(y,100,H-30),type,hp:spec[0]*(1+(wave-1)*.16),max:spec[0]*(1+(wave-1)*.16),speed:spec[1],r:spec[2],color:spec[3],phase:rnd(0,TAU),cd:rnd(1,3),hit:0});}
function spawnBoss(){bossStarted=true;boss={x:CX,y:165,type:'boss',hp:2600,max:2600,r:66,color:'#dc7e85',phase:0,cd:1,hit:0};enemies.push(boss);toast('LEVIATHAN  ·  THE SEA HAS A HEART. BREAK IT.');shake=12;ring(CX,165,'#ef819b',420);}
function damageEnemy(e,d){if(e.hp<=0)return;e.hp-=d;e.hit=.1;if(e.hp<=0){kills++;score+=e.type==='boss'?2500:e.type==='brute'?150:60;burst(e.x,e.y,e.color,e.type==='boss'?100:18,190);sound(e.type==='brute'?90:170,.12,'triangle',.025,.4);shake=Math.max(shake,e.type==='boss'?20:2);if(e.type!=='boss'){drops.push({x:e.x,y:e.y,kind:Math.random()<.18?'heal':'gold',age:0});}else{boss=null;finish(true);}}}
function hurt(amount){if(state!=='playing'||player.inv>0)return;player.hp-=amount*(easy?.65:1);player.inv=.7;shake=8;burst(player.x,player.y,'#f4b7a2');sound(80,.2,'sawtooth',.07,.4);if(player.hp<=0){player.hp=0;finish(false,'Your skiff was lost beneath the waves.');}}
function dash(){if(state!=='playing'||player.dash>0)return;let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const l=Math.hypot(x,y);if(l){player.dx=x/l;player.dy=y/l;}player.dashTime=.2;player.inv=.35;player.dash=2.4*(player.dashMod||1);sound(260,.15,'sawtooth',.045,.3);}
function pulse(){if(state!=='playing'||player.pulse>0)return;player.pulse=player.pulseMax;ring(player.x,player.y,'#95f6e2',300);burst(player.x,player.y,'#a3f2df',35,350);for(const e of enemies)if(dist(e,player)<300)damageEnemy(e,player.pulseDamage||50);hostile=hostile.filter(b=>dist(b,player)>310);shake=6;sound(130,.6,'sine',.18,3);}
function fire(){let target=null,bestD=620;for(const e of enemies){const d=dist(e,player);if(e.hp>0&&d<bestD){target=e;bestD=d;}}if(!target&&!mouse.down)return;const aim=mouse.down?mouse:target,a=Math.atan2(aim.y-player.y,aim.x-player.x);player.angle=a;for(let j=0;j<player.multi;j++){const angle=a+(j-(player.multi-1)/2)*.12;shots.push({x:player.x+Math.cos(angle)*20,y:player.y+Math.sin(angle)*20,vx:Math.cos(angle)*650,vy:Math.sin(angle)*650,life:1.05,pierce:player.pierce,hit:new Set()});}sound(600,.045,'triangle',.024,.6);player.fire=player.rate;}
function enemyShot(e,a,speed=155){hostile.push({x:e.x,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:9,r:6});}
function update(dt){clock+=dt;notice-=dt;if(notice<=0)$('toast').textContent='';for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt;}particles=particles.filter(p=>p.life>0);for(const r of rings){r.r+=(r.max-r.r)*dt*7;r.life-=dt;}rings=rings.filter(r=>r.life>0);shake=Math.max(0,shake-dt*25);if(state!=='playing')return;runTime+=dt;music(dt);waveTime+=dt;player.inv-=dt;player.dash=Math.max(0,player.dash-dt);player.pulse=Math.max(0,player.pulse-dt);player.fire-=dt;player.hp=Math.min(player.max,player.hp+player.regen*dt);
let mx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),my=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),len=Math.hypot(mx,my);
if(player.dashTime>0){player.dashTime-=dt;player.x+=player.dx*900*dt;player.y+=player.dy*900*dt;burst(player.x,player.y,'#a7eada',2,35);}else if(len){player.dx=mx/len;player.dy=my/len;player.x+=mx/len*player.speed*dt;player.y+=my/len*player.speed*dt;if(Math.random()<.5)burst(player.x-player.dx*13,player.y-player.dy*13,'#427e83',1,25);}
player.x=clamp(player.x,28,W-28);player.y=clamp(player.y,115,H-38);let dc=Math.hypot(player.x-CX,player.y-CY);if(dc<67){const a=Math.atan2(player.y-CY,player.x-CX);player.x=CX+Math.cos(a)*67;player.y=CY+Math.sin(a)*67;}
if(player.fire<=0)fire();
const duration=32+wave*3;
if(waveTime<duration){spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=Math.max(.35,1.5-wave*.19);let t=Math.random();spawn(wave>=3&&t<.17?'brute':wave>=2&&t<.36?'spitter':t<.62?'hunter':'drifter');if(wave>=4&&Math.random()<.35)spawn('drifter');}}else if(wave===5&&!bossStarted)spawnBoss();
for(const e of enemies){if(e.hp<=0)continue;e.phase+=dt;e.hit-=dt;e.cd-=dt;if(e.type==='boss'){e.x=CX+Math.sin(e.phase*.45)*360;e.y=235+Math.sin(e.phase*.8)*100;if(e.cd<=0){e.cd=e.hp<e.max*.5?.8:1.25;const base=Math.atan2(player.y-e.y,player.x-e.x);for(let j=-2;j<=2;j++)enemyShot(e,base+j*.18,190);for(let j=0;j<12;j++)enemyShot(e,j*TAU/12+e.phase*.4,115);if(Math.random()<.35)spawn('hunter');}}else{const target=e.type==='hunter'?player:{x:CX,y:CY};const a=Math.atan2(target.y-e.y,target.x-e.x),d=dist(e,target);if(e.type==='spitter'&&d<290){if(e.cd<=0){e.cd=2.8;enemyShot(e,Math.atan2(player.y-e.y,player.x-e.x));}}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}
if(dist(e,{x:CX,y:CY})<e.r+48){beacon-=dt*(e.type==='brute'?7:3.5)*(easy?.65:1);if(e.cd<=0){e.cd=.6;burst(CX,CY,'#e9c88d',3,100);}}}
if(dist(e,player)<e.r+13){if(player.dashTime>0){if(!e.dashHit||runTime-e.dashHit>.4){damageEnemy(e,65);e.dashHit=runTime;}}else hurt(e.type==='boss'?30:16);}}
if(state!=='playing')return;
for(const b of shots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies){if(e.hp>0&&!b.hit.has(e)&&dist(b,e)<e.r+5){b.hit.add(e);damageEnemy(e,player.damage);burst(b.x,b.y,'#f8d893',3,65);if(b.pierce--<=0){b.life=0;break;}}}}shots=shots.filter(b=>b.life>0);
if(state!=='playing')return;
for(const b of hostile){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(dist(b,player)<19){hurt(12);b.life=0;}}hostile=hostile.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);
for(const d of drops){d.age+=dt;let dd=dist(d,player);if(dd<player.magnet){d.x+=(player.x-d.x)*dt*7;d.y+=(player.y-d.y)*dt*7;}if(dd<22){d.gone=true;score+=20;if(d.kind==='heal')player.hp=Math.min(player.max,player.hp+16);else beacon=Math.min(100,beacon+(easy?4:2.5));sound(d.kind==='heal'?700:900,.08,'sine',.025,1.4);}}drops=drops.filter(d=>!d.gone&&d.age<24);enemies=enemies.filter(e=>e.hp>0);
if(state!=='playing')return;if(beacon<=0){beacon=0;finish(false,'The lighthouse fell silent.');}else if(waveTime>=duration&&enemies.length===0&&wave<5)dock();}
function background(){ctx.fillStyle='#07191f';ctx.fillRect(0,0,W,H);const g=ctx.createRadialGradient(CX,CY,20,CX,CY,750);g.addColorStop(0,'#173e42');g.addColorStop(.45,'#0b262e');g.addColorStop(1,'#040e16');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.lineWidth=1;
for(let j=0;j<19;j++){ctx.strokeStyle=`rgba(100,165,172,${.045+(j%3)*.009})`;ctx.beginPath();for(let x=0;x<=W;x+=20){const y=110+j*44+Math.sin(x*.008+clock*.28+j*.9)*13+Math.sin(x*.018-clock*.3)*5;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}
for(const s of stars)circle(s.x,s.y,s.r,`rgba(151,202,193,${.11+Math.sin(clock+s.p)*.08})`);
ctx.save();ctx.translate(CX,CY);ctx.rotate(clock*.22);const beam=ctx.createRadialGradient(0,0,20,0,0,670);beam.addColorStop(0,'#e8cc8630');beam.addColorStop(1,'#e8cc8600');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,670,-.2,.2);ctx.closePath();ctx.fill();ctx.rotate(Math.PI);ctx.fill();ctx.restore();
// A low island, concentric ripples, and a tiny architectural lighthouse.
for(let i=0;i<3;i++){ctx.strokeStyle=`rgba(150,209,199,${.09-i*.02})`;ctx.beginPath();ctx.ellipse(CX,CY+20,78+i*24+Math.sin(clock)*3,44+i*13,0,0,TAU);ctx.stroke();}
ctx.fillStyle='#122629';ctx.beginPath();for(let i=0;i<12;i++){const a=i*TAU/12,r=55+(i%3)*5;const x=CX+Math.cos(a)*r,y=CY+19+Math.sin(a)*r*.65;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();ctx.fillStyle='#345152';ctx.fillRect(CX-16,CY-29,32,62);ctx.fillStyle='#223b3e';ctx.fillRect(CX+4,CY-29,12,62);ctx.fillStyle='#b39f78';ctx.fillRect(CX-19,CY-32,38,7);ctx.fillStyle='#eecf8f';ctx.fillRect(CX-11,CY-49,22,17);ctx.fillStyle='#395b5b';ctx.beginPath();ctx.moveTo(CX-22,CY-50);ctx.lineTo(CX,CY-65);ctx.lineTo(CX+22,CY-50);ctx.fill();const glow=ctx.createRadialGradient(CX,CY-40,2,CX,CY-40,75);glow.addColorStop(0,'#ffe2a970');glow.addColorStop(1,'#ffe2a900');ctx.fillStyle=glow;ctx.fillRect(CX-80,CY-120,160,160);
}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);const a=e.type==='boss'?Math.PI/2:Math.atan2(CY-e.y,CX-e.x);ctx.rotate(a);ctx.strokeStyle=e.color;ctx.lineWidth=e.type==='boss'?5:2;const n=e.type==='boss'?8:4;for(let j=0;j<n;j++){const side=j%2?1:-1,offset=(Math.floor(j/2)-n/4)*e.r*.6;ctx.beginPath();ctx.moveTo(offset,side*e.r*.4);ctx.quadraticCurveTo(offset-e.r*.7,side*e.r*(1.1+Math.sin(e.phase*4+j)*.25),offset-e.r*1.1,side*e.r*1.3);ctx.stroke();}ctx.fillStyle=e.hit>0?'#fff2d3':e.color;ctx.beginPath();ctx.ellipse(0,0,e.r,e.r*.65,0,0,TAU);ctx.fill();ctx.fillStyle='#162e32';ctx.beginPath();ctx.ellipse(-3,0,e.r*.72,e.r*.43,0,0,TAU);ctx.fill();circle(e.r*.5,-e.r*.23,e.r*.13,'#ffe4b8');circle(e.r*.5,e.r*.23,e.r*.13,'#ffe4b8');ctx.restore();if(e.hp<e.max&&e.type!=='boss'){ctx.fillStyle='#14242c';ctx.fillRect(e.x-20,e.y-e.r-16,40,3);ctx.fillStyle=e.color;ctx.fillRect(e.x-20,e.y-e.r-16,40*e.hp/e.max,3);}}
function drawPlayer(){if(!player)return;ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.angle??-Math.PI/2);if(player.inv>0&&Math.floor(clock*18)%2===0)ctx.globalAlpha=.5;ctx.shadowColor='#92e9dc';ctx.shadowBlur=15;ctx.fillStyle='#bfe8db';ctx.beginPath();ctx.moveTo(23,0);ctx.lineTo(-14,-12);ctx.lineTo(-9,0);ctx.lineTo(-14,12);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#315258';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-6);ctx.lineTo(-5,6);ctx.closePath();ctx.fill();circle(-5,0,3,'#ffe0a0');ctx.restore();if(player.dashTime>0){ctx.strokeStyle='#b8fff0';ctx.beginPath();ctx.arc(player.x,player.y,28,0,TAU);ctx.stroke();}}
function bar(x,y,w,value,color){ctx.fillStyle='#21393e';ctx.fillRect(x,y,w,5);ctx.fillStyle=color;ctx.fillRect(x,y,w*clamp(value,0,1),5);}
function hud(){ctx.fillStyle='#06141aea';ctx.fillRect(0,0,W,88);ctx.strokeStyle='#274047';ctx.beginPath();ctx.moveTo(25,88);ctx.lineTo(W-25,88);ctx.stroke();text('LASTLIGHT',30,38,23,'#edd39c');text('KEEP THE FIRE. HOLD THE SEA.',31,62,9,'#78979b');text('HULL',260,31,10,'#8cadad');text(`${Math.ceil(player.hp)} / ${player.max}`,430,31,12,'#b7dfd5','right');bar(260,44,170,player.hp/player.max,'#9ce1ce');text('LANTERN',475,31,10,'#8cadad');text(`${Math.ceil(beacon)}%`,645,31,12,'#edcf93','right');bar(475,44,170,beacon/100,beacon<30?'#ed8379':'#edcf93');text(`TIDE 0${wave} / 05`,720,34,16,'#e4d7b7');const duration=32+wave*3;text(boss?'DEFEAT THE LEVIATHAN':waveTime>=duration?'CLEAR THE REMAINING CREATURES':`${Math.ceil(duration-waveTime)}s · ${names[wave-1]}`,720,58,10,'#8cabaf');text(score.toLocaleString().padStart(6,'0'),1190,38,25,'#d8e7e1','right');text('SALVAGE SCORE',1190,59,9,'#8cabaf','right');text(muted?'M · MUTED':'M · SOUND',1240,32,11,'#89a8ad');text('P · PAUSE',1240,55,11,'#89a8ad');
ctx.fillStyle='#081a20df';ctx.fillRect(25,H-71,325,48);text(`SPACE  ${player.dash>0?player.dash.toFixed(1)+'s':'DASH READY'}`,40,H-49,11,player.dash>0?'#78979b':'#b9e8db');text(`E  ${player.pulse>0?player.pulse.toFixed(1)+'s':'PULSE READY'}`,205,H-49,11,player.pulse>0?'#78979b':'#edcf93');bar(40,H-38,130,1-player.dash/(2.4*(player.dashMod||1)),'#a0dacc');bar(205,H-38,130,1-player.pulse/player.pulseMax,'#edcf93');text('GOLD → LANTERN   /   GREEN → HULL',W-30,H-33,11,'#8caaa9','right');
if(boss){text('L E V I A T H A N',CX,115,12,'#e2a3aa','center');bar(CX-230,126,460,boss.hp/boss.max,'#d88796');}if(beacon<30&&Math.sin(clock*5)>0)text('LANTERN CRITICAL — COLLECT GOLD SALVAGE',CX,158,15,'#ff9c86','center');}
function render(){const d=Math.min(devicePixelRatio||1,2);ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#030b10';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.translate(ox,oy);ctx.scale(scale,scale);ctx.save();ctx.beginPath();ctx.rect(0,0,W,H);ctx.clip();if(shake&&state==='playing')ctx.translate(rnd(-shake,shake),rnd(-shake,shake));background();for(const drop of drops){const color=drop.kind==='heal'?'#97e3b4':'#edc886';ctx.save();ctx.translate(drop.x,drop.y);ctx.rotate(clock+drop.age);ctx.shadowColor=color;ctx.shadowBlur=12;ctx.fillStyle=color;ctx.fillRect(-4,-4,8,8);ctx.restore();}for(const e of enemies)if(e.hp>0)drawEnemy(e);for(const b of shots){ctx.strokeStyle='#f8d898';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.022,b.y-b.vy*.022);ctx.stroke();}for(const b of hostile){circle(b.x,b.y,10,'#f27e8b25');circle(b.x,b.y,5,'#f79a9b');}drawPlayer();for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);circle(p.x,p.y,p.r,p.color);}ctx.globalAlpha=1;for(const r of rings){ctx.globalAlpha=r.life*2;ctx.strokeStyle=r.color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke();}ctx.globalAlpha=1;ctx.restore();if(player&&state!=='menu')hud();if(state==='playing'&&mouse.down){ctx.strokeStyle='#d8e9cf80';ctx.beginPath();ctx.arc(mouse.x,mouse.y,12,0,TAU);ctx.moveTo(mouse.x-17,mouse.y);ctx.lineTo(mouse.x+17,mouse.y);ctx.moveTo(mouse.x,mouse.y-17);ctx.lineTo(mouse.x,mouse.y+17);ctx.stroke();}}
function pause(){if(state==='playing'){state='paused';$('pause').classList.remove('hidden');keys.clear();mouse.down=false;}else if(state==='paused'){state='playing';$('pause').classList.add('hidden');}}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='p'||k==='escape')pause();if(k===' ')dash();if(k==='e')pulse();if(k==='m'){muted=!muted;toast(muted?'SOUND OFF':'SOUND ON');}if(k==='f'){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});}if(state==='upgrade'&&['1','2','3'].includes(k))choose(Number(k)-1);});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();mouse.down=false;if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});canvas.addEventListener('mousemove',e=>{mouse.x=(e.clientX-ox)/scale;mouse.y=(e.clientY-oy)/scale;});canvas.addEventListener('mousedown',e=>{if(e.button===0)mouse.down=true;});addEventListener('mouseup',()=>mouse.down=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('start').onclick=begin;$('restart').onclick=begin;$('resume').onclick=pause;$('back').onclick=()=>{hide();state='menu';player=null;enemies=[];shots=[];hostile=[];drops=[];$('menu').classList.remove('hidden');$('best').textContent=`FIVE TIDES. ONE LEVIATHAN. ONE DAWN.    /    BEST ${best.toLocaleString()}`;};$('difficulty').onclick=()=>{easy=!easy;$('difficulty').textContent=`Mode: ${easy?'Navigator (gentler)':'Mariner'}`;};
function frame(t){const dt=Math.min((t-last)/1000,.05);last=t;acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60;}render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
// Small read-only diagnostics surface for local verification.
window.lastlight={snapshot:()=>({state,wave,score,kills,beacon,hp:player?.hp,enemies:enemies.length,boss:!!boss,runTime}),};
})();
